### ISSUE TITLE
bug: sql: expected 19 destination arguments in Scan

### ISSUE THREAD

**Issue by hnlq715** [douyu/juno#382]
加载应用列表失败:sql: expected 19 destination arguments in Scan, not 1; sql: expected 19 destination arguments in Scan, not 1
![截屏2023-02-16 11 09 49](https://user-images.githubusercontent.com/1734615/219258540-f3d0b115-2ead-4618-8128-b9b0893afcee.jpeg)

**Comment by linthan** [comment]
#373 #376  因为gorm v2 client 并发查询导致的. 消除并发就可以解决
