### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by linthan** [douyu/juno#41]
1 建议前端把核心依赖包，用过external的方式分离出来,主要是为了控制编译包的大小。提升加载体验。 
2 应用配置，保存的时候给一个diff的展示，保存起来更放心。
3 可以参考pretty playgroud项目。 service worker的方式来格式化配置。
https://github.com/prettier/prettier/blob/master/website/static/worker.js
prettier-plugin-toml : https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml

**Comment by MEX7** [comment]
1. 打包的方面后期会这样计划搞，当前加载效率较低的就是配置中心编辑器的核心js；另外打算将dist目录停止代码库上传，控制代码库的大小。
2. 已经在0.3.0计划中了，最近2周会完成开发。
3. 已经在0.3.0计划中了，最近2周会完成开发。


@askuy @link-duan
