### ISSUE TITLE
希望加个juno + jupter 全套的docker-compose file, 一键测试部署，方便开发者试用

### ISSUE THREAD

**Issue by tx991020** [douyu/juno#44]
希望加个juno + jupter 全套的docker-compose file, 一键测试部署，方便开发者试用

**Comment by tx991020** [comment]
最好还加个ant-design 前端的表单生成器，生成表单，这样后端能写一些简单的监控界面

**Comment by MEX7** [comment]
> 希望加个juno + jupter 全套的docker-compose file, 一键测试部署，方便开发者试用

这里有个juno-install的项目https://github.com/douyu/juno-install，看有没有帮助，是juno这边的demo部署实践。
