### ISSUE TITLE
首页/配置中心/资源，list页面显示Bug

### ISSUE THREAD

**Issue by younglifestyle** [douyu/juno#48]
接口返回：
![image](https://user-images.githubusercontent.com/19261307/88496312-55b0b980-cfef-11ea-9604-3313e4cc6395.png)

而实际页面下标依然只显示到第一页。
![image](https://user-images.githubusercontent.com/19261307/88496369-7f69e080-cfef-11ea-90d0-f1f2680506ad.png)

**Comment by link-duan** [comment]
已修复 https://github.com/douyu/juno/commit/13235045aed8b7962476be150792d8c99b3feca4
