### ISSUE TITLE
The ids here are defined as a global variable, which is a bad design

### ISSUE THREAD

**Issue by daheige** [douyu/juno#5]
https://github.com/douyu/juno/blob/f9c07d443c563ab3bca9b21525dd8097b4c4cc79/pkg/library/depTree.go#L40

The ids here are defined as a global variable. If it is in a project, if the function in this package is called multiple times to process the tree, it is easy to cause pollution of the ids variable. Can the depTree operation and ids be placed As a local variable in the structure. In addition, the naming of this file is very irregular, sometimes uppercase, sometimes lowercase, can you refer to the uber-go guide code specification or the industry go code specification, you can also use the golang-ci tool to do code standardization adjustments to your code What?

**Comment by askuy** [comment]
Thank you for your advice
