### ISSUE TITLE
关于juno使用的一些建议

### ISSUE THREAD

**Issue by tanjiancheng** [douyu/juno#56]
我通过juno-install搭建了juno的后台管理界面，但是我并不清楚这块怎么跟jupiter结合使用，相关的文档看着雾里云烟的，能不能给个全家桶能体验相关的jupiter和juno的功能，另外关于服务链路跟踪和服务指标收集能不能有方式可以单独接入jaeger和prometheus的？

**Comment by dcsunny** [comment]
+1 我看不懂，不知道部署的jupiter项目，怎么到juno系统中，并且知道jupiter项目怎么使用agent

**Comment by younglifestyle** [comment]
+1

**Comment by MEX7** [comment]
之前的文档不太注重关联性，我们这边正在补充相关文档。
