### ISSUE TITLE
要将日志轮换周期改为48小时,配置文件中interval=？（interval=48还是interval=48h还是interval=48*time.Hour还是？）

### ISSUE THREAD

**Issue by wangyx6666** [douyu/juno#583]

**Comment by linthan** [comment]
代码里面是一个duration，类型 例如： Interval:      24 * time.Hour。

**Comment by wangyx6666** [comment]
interval=48h,报错了
 default load config from datasource[config/single-region-admin.toml] failed: toml: line 20 (last key "logger.system"): expected a top-level item to end with a newline, comment, or EO
F, but got 'h' instead

**Comment by wangyx6666** [comment]
![{~5(X5 T5UI S7} KQR8JX](https://github.com/douyu/juno/assets/109134231/14245b9a-14c6-4ba2-8117-b03211979524)

**Comment by linthan** [comment]
加上冒号，这种属于string解析

**Comment by linthan** [comment]
interval="48h"

**Comment by wangyx6666** [comment]
还有一个问题
![image](https://github.com/douyu/juno/assets/109134231/449f65e6-8e1b-4fe5-9e53-1d89cf24e0d0)
这有三种日志类型，可是只有两个json文件
![image](https://github.com/douyu/juno/assets/109134231/dae175ce-0b3d-4537-b14b-d7d2050864de)

**Comment by wangyx6666** [comment]
看配置也只写了两个
![image](https://github.com/douyu/juno/assets/109134231/430dc3ee-0683-453c-bdaf-480413837bb0)

**Comment by linthan** [comment]
还一部分是console日志。你的supervisor 进程管理的日志。
