### ISSUE TITLE
Can the routing addresses in this routing file be standardized?

### ISSUE THREAD

**Issue by daheige** [douyu/juno#6]
https://github.com/douyu/juno/blob/f9c07d443c563ab3bca9b21525dd8097b4c4cc79/router/router.go#L330

The routing address in this routing file, sometimes uppercase, sometimes lowercase, can it be unified and standardized? There is also a lot of routing addresses that do not comply with the restful API specifications. Can this be improved?

**Comment by MEX7** [comment]
we fixed this problem in this commit [https://github.com/douyu/juno/commit/06adb56106eabc313da9a624e09aa7a82d571cad](https://github.com/douyu/juno/commit/06adb56106eabc313da9a624e09aa7a82d571cad)

tks, very much
