### ISSUE TITLE
The golang code specification is in place, can it be improved?

### ISSUE THREAD

**Issue by daheige** [douyu/juno#7]
https://github.com/douyu/juno/blob/f9c07d443c563ab3bca9b21525dd8097b4c4cc79/pkg/handler/app/req.go#L3

There is no necessary comment for the code that needs to be exported. I read a lot of your Juno code and found that many of the codes are not standardized. Can you refer to golang-ci to run the code inspection and normalization process, and then rectify your code? Like base, utils, tools, base dir, pkg/library, many code files and directories are not named properly, and there are some projects and component code organizations that are not standardized. Can you refer to https://draveness.me/golang-101/ and https://github.com/uber-go/guide and https://github.com/golang-standards/project-layout for some suggestions? , And then refer to https://github.com/golangci/golangci-lint to improve the code, directory, naming, etc.?

**Comment by askuy** [comment]
Thank you for your advice
