### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by FTwOoO** [douyu/juno#72]
唉，能不能把安装搞简单点，各种方式都试了，还看了下Dockerfile，也没装成功，
go的项目一般binary加几个参数或者docker run加参数就跑起来了，juno怎么这么难呢

**Comment by MEX7** [comment]
可以提供具体的报错信息，这边协助排查。

**Comment by hnlq715** [comment]
建议贴上具体错误信息，这个issue先close，欢迎随时reopen
