### ISSUE TITLE
添加 toml formatter 功能

### ISSUE THREAD

**Issue by linthan** [douyu/juno#9]
问题：目前使用的是go-toml这个工具库,来格式化配置文件，存在丢注释的情况，而且本身的作者也无心添加这个特性。而且把以前写过的注释解析函数还删除了
[讨论](https://github.com/pelletier/go-toml/milestone/5)
作者的原话:
Currently, the encoding mechanism does not use the position information, and sorts the keys instead. That would need to be changed in order to be able to preserve comments (otherwise multiline comments wouldn't make sense anymore).
解决方案：
使用 prettier直接在前端进行format。 目前prettier是通过插件的方式来支持toml文件的（pritter-plugin-toml）
好处：
1. 可以方便项目以后格式化 yaml,json等等一系列配置文件，都使用同一个库（prettier）而不是在go的一些额外库中对每种文件进行支持，更统一，更方便
2.  因为vscode的存在(typescript写的)，本身IDE属性加持，用js来做这样的活比golang更适合一些，社区也更活跃一些。
解决方案和目前存在方案的差异：
因为本身解析方式的不同。导致缩进的格式不是嵌套的。 个人这样觉得反而会更清晰。 prettier提供的format的方式没有进行排序。 golang的提供了排序（也是因为这个导致加注释信息有些困难）

**Comment by MEX7** [comment]
我觉得很可以。目前我这边有个版本是保留了配置注释的。本周进行开发：
- 参考namesapce的方案优化前端交互
- 预览界面按照你的方案进行前端格式化
